version: 2.1
jobs:
  build:
    working_directory: ~/feature-toggle
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1
    steps:
      - checkout
      - run:
          name: Restore Packages
          command: dotnet restore
      - run:
          name: Build
          command: dotnet build
      - run:
          name: Tests
          command: dotnet test
